package view;

import controller.ProductoController;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import model.Producto;

public class InternalFrmCliente extends javax.swing.JInternalFrame {

    public InternalFrmCliente() {
        initComponents();

        this.setSize(new Dimension(400, 300));
        this.setTitle("Nuevo Cliente");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ctNomCli = new javax.swing.JTextField();
        ctSurNameCli = new javax.swing.JTextField();
        ctDNICli = new javax.swing.JTextField();
        ctTelCli = new javax.swing.JTextField();
        btnGuaCli = new javax.swing.JButton();
        ctDirCli = new javax.swing.JTextField();
        fondo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nuevo Cliente");
        jLabel3.setAlignmentX(140.0F);
        jLabel3.setAlignmentY(10.0F);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Telefono");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 20));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Numero de DNI:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 20));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 140, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Apellido:");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 20));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Nombre:");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 20));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Direccion: ");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 20));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        ctNomCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctNomCliActionPerformed(evt);
            }
        });
        getContentPane().add(ctNomCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 170, -1));

        ctSurNameCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctSurNameCliActionPerformed(evt);
            }
        });
        getContentPane().add(ctSurNameCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 170, -1));

        ctDNICli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctDNICliActionPerformed(evt);
            }
        });
        getContentPane().add(ctDNICli, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 170, -1));

        ctTelCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctTelCliActionPerformed(evt);
            }
        });
        getContentPane().add(ctTelCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 170, -1));

        btnGuaCli.setBackground(new java.awt.Color(0, 255, 51));
        btnGuaCli.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuaCli.setForeground(new java.awt.Color(255, 255, 255));
        btnGuaCli.setText("Guardar");
        btnGuaCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuaCliActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuaCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 150, -1));

        ctDirCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctDirCliActionPerformed(evt);
            }
        });
        getContentPane().add(ctDirCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 170, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo3.jpg"))); // NOI18N
        fondo.setText("Nuevo Producto");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ctNomCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctNomCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctNomCliActionPerformed

    private void ctSurNameCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctSurNameCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctSurNameCliActionPerformed

    private void ctDNICliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctDNICliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctDNICliActionPerformed

    private void ctTelCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctTelCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctTelCliActionPerformed

    private void btnGuaCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuaCliActionPerformed
        
    }//GEN-LAST:event_btnGuaCliActionPerformed

    private void ctDirCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctDirCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctDirCliActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuaCli;
    private javax.swing.JTextField ctDNICli;
    private javax.swing.JTextField ctDirCli;
    private javax.swing.JTextField ctNomCli;
    private javax.swing.JTextField ctSurNameCli;
    private javax.swing.JTextField ctTelCli;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

    public void limpiarcampos() {
        ctNomCli.setText("");
        ctSurNameCli.setText("");
        ctDNICli.setText("");
        ctTelCli.setText("");
    }

}
