
package view;

import java.awt.Dimension;


public class InternalFrmProducto extends javax.swing.JInternalFrame {
    
    
    public InternalFrmProducto() {
        initComponents();
        
        this.setSize(new Dimension(400, 300));
        this.setTitle("Nuevo Producto"); 
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ctNomProd = new javax.swing.JTextField();
        ctCantProd = new javax.swing.JTextField();
        ctPrecProd = new javax.swing.JTextField();
        ctDesProd = new javax.swing.JTextField();
        selIVAProd = new javax.swing.JComboBox<>();
        btnGuaProd = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nuevo Producto");
        jLabel3.setAlignmentX(140.0F);
        jLabel3.setAlignmentY(10.0F);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Descripcion");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 20));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Precio:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 20));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Cantidad:");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 20));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Nombre:");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 20));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("IVA: ");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 20));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        ctNomProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctNomProdActionPerformed(evt);
            }
        });
        getContentPane().add(ctNomProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 170, -1));

        ctCantProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctCantProdActionPerformed(evt);
            }
        });
        getContentPane().add(ctCantProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 170, -1));

        ctPrecProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctPrecProdActionPerformed(evt);
            }
        });
        getContentPane().add(ctPrecProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 170, -1));

        ctDesProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctDesProdActionPerformed(evt);
            }
        });
        getContentPane().add(ctDesProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 170, -1));

        selIVAProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Sin IVA", "5%", "19%", "32%" }));
        getContentPane().add(selIVAProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 170, -1));

        btnGuaProd.setBackground(new java.awt.Color(0, 255, 51));
        btnGuaProd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuaProd.setForeground(new java.awt.Color(255, 255, 255));
        btnGuaProd.setText("Guardar");
        getContentPane().add(btnGuaProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 150, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo3.jpg"))); // NOI18N
        fondo.setText("Nuevo Producto");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ctNomProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctNomProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctNomProdActionPerformed

    private void ctCantProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctCantProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctCantProdActionPerformed

    private void ctPrecProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctPrecProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctPrecProdActionPerformed

    private void ctDesProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctDesProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctDesProdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuaProd;
    private javax.swing.JTextField ctCantProd;
    private javax.swing.JTextField ctDesProd;
    private javax.swing.JTextField ctNomProd;
    private javax.swing.JTextField ctPrecProd;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> selIVAProd;
    // End of variables declaration//GEN-END:variables
}
